spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pcmarket
    username: postgres
    password: 9698
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  data:
    rest:
      base-path: api
attachment:
  download:
    url: /api/attachment/download/